language: php

php:
  # aliased to a recent 7.0.x version
  - 7.0

before_script:
  - composer self-update
  - composer install -vvv
  - composer dump-autoload --optimize
script: phpunit --bootstrap phpunit.php

matrix:
  fast_finish: true